# docker-compose.override.yml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"  # Expones React en http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necesario para hot reload en Docker

  backend:
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
